language: node_js
node_js:
  - "12"
cache: yarn
deploy:
  local_dir: .docs
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
    condition: '"$TRAVIS_JOB_NUMBER" == *.1'
script:
  - "(yarn lint && yarn test --ci --coverage) || travis_terminate"
  - 'if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then yarn build:storybook || travis_terminate 1; fi'
  - yarn release
after_success:
  - bash <(curl -s https://codecov.io/bash)
