name: Jest tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
defaults:
  runs-on: ubuntu-latest
env:
  NODE: 14



jobs:
  build_test:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ github.env.NODE }}
      - name: Install modules
        run: yarn
      - name: Run tests with coverage
        run: yarn test --ci --coverage
      - name: Submit codecov results
        uses: codecov/codecov-action@v1
  deploy:
    needs: build_test
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Generate storybook documentation
        run: yarn build:storybook
  release:
    needs: [ build_test, deploy ]
    if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
    steps:
      - name: Release new version
        run: yarn release
